export const HIDE_MODAL = 'HIDE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const SET_AUDIT_SUMMARY = 'SET_AUDIT_SUMMARY';
export const SET_CSS = 'SET_CSS';
export const TOGGLE_ALL_BROWSERS = 'TOGGLE_ALL_BROWSERS';
export const TOGGLE_BROWSER = 'TOGGLE_BROWSER';
export const TOGGLE_BROWSER_VERSION = 'TOGGLE_BROWSER_VERSION';
export const TOGGLE_FEATURE_DECLARATIONS_LIMIT = 'TOGGLE_FEATURE_DECLARATIONS_LIMIT';
