export default {
  and_chr: 'Chrome for Android',
  and_ff: 'Firefox for Android',
  and_qq: 'QQ Browser',
  and_uc: 'UC Browser for Android',
  android: 'Android Browser',
  baidu: 'Baidu Browser',
  bb: 'Blackberry Browser',
  chrome: 'Chrome',
  edge: 'Edge',
  firefox: 'Firefox',
  ie: 'IE',
  ie_mob: 'IE Mobile',
  ios_saf: 'iOS Safari',
  // op_mini: 'Opera Mini',
  op_mob: 'Opera Mobile',
  opera: 'Opera',
  safari: 'Safari',
  samsung: 'Samsung Internet',
};
