export default {
  and_chr: 'ChromeAndroid',
  and_ff: 'FirefoxAndroid',
  and_qq: 'QQAndroid',
  and_uc: 'UCAndroid',
  android: 'Android',
  baidu: 'Baidu',
  bb: 'BlackBerry',
  chrome: 'Chrome',
  edge: 'Edge',
  firefox: 'Firefox',
  ie: 'Explorer',
  ie_mob: 'ExplorerMobile',
  ios_saf: 'iOS',
  // op_mini: 'OperaMini',
  op_mob: 'OperaMobile',
  opera: 'Opera',
  safari: 'Safari',
  samsung: 'Samsung',
};
